spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect